# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buyer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62uyer.proto\"\x8a\x01\n\x04Item\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nitem_price\x18\x03 \x01(\x02\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x16\n\x0eseller_address\x18\x07 \x01(\t\"=\n\x11SearchItemRequest\x12\x11\n\titem_name\x18\x01 \x01(\t\x12\x15\n\rcategory_name\x18\x02 \x01(\t\"*\n\x12SearchItemResponse\x12\x14\n\x05items\x18\x01 \x03(\x0b\x32\x05.Item\"8\n\x0e\x42uyItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x15\n\ritem_quantity\x18\x02 \x01(\x05\"^\n\x0f\x42uyItemResponse\x12\'\n\x06status\x18\x01 \x01(\x0e\x32\x17.BuyItemResponse.Status\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\"\'\n\x14\x41\x64\x64ToWishListRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\"j\n\x15\x41\x64\x64ToWishListResponse\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.AddToWishListResponse.Status\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\"2\n\x0fRateItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x0e\n\x06rating\x18\x02 \x01(\x05\"`\n\x10RateItemResponse\x12(\n\x06status\x18\x01 \x01(\x0e\x32\x18.RateItemResponse.Status\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32\xe4\x01\n\x0c\x42uyerService\x12\x35\n\nSearchItem\x12\x12.SearchItemRequest\x1a\x13.SearchItemResponse\x12,\n\x07\x42uyItem\x12\x0f.BuyItemRequest\x1a\x10.BuyItemResponse\x12>\n\rAddToWishList\x12\x15.AddToWishListRequest\x1a\x16.AddToWishListResponse\x12/\n\x08RateItem\x12\x10.RateItemRequest\x1a\x11.RateItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buyer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEM']._serialized_start=16
  _globals['_ITEM']._serialized_end=154
  _globals['_SEARCHITEMREQUEST']._serialized_start=156
  _globals['_SEARCHITEMREQUEST']._serialized_end=217
  _globals['_SEARCHITEMRESPONSE']._serialized_start=219
  _globals['_SEARCHITEMRESPONSE']._serialized_end=261
  _globals['_BUYITEMREQUEST']._serialized_start=263
  _globals['_BUYITEMREQUEST']._serialized_end=319
  _globals['_BUYITEMRESPONSE']._serialized_start=321
  _globals['_BUYITEMRESPONSE']._serialized_end=415
  _globals['_BUYITEMRESPONSE_STATUS']._serialized_start=381
  _globals['_BUYITEMRESPONSE_STATUS']._serialized_end=415
  _globals['_ADDTOWISHLISTREQUEST']._serialized_start=417
  _globals['_ADDTOWISHLISTREQUEST']._serialized_end=456
  _globals['_ADDTOWISHLISTRESPONSE']._serialized_start=458
  _globals['_ADDTOWISHLISTRESPONSE']._serialized_end=564
  _globals['_ADDTOWISHLISTRESPONSE_STATUS']._serialized_start=381
  _globals['_ADDTOWISHLISTRESPONSE_STATUS']._serialized_end=415
  _globals['_RATEITEMREQUEST']._serialized_start=566
  _globals['_RATEITEMREQUEST']._serialized_end=616
  _globals['_RATEITEMRESPONSE']._serialized_start=618
  _globals['_RATEITEMRESPONSE']._serialized_end=714
  _globals['_RATEITEMRESPONSE_STATUS']._serialized_start=381
  _globals['_RATEITEMRESPONSE_STATUS']._serialized_end=415
  _globals['_BUYERSERVICE']._serialized_start=717
  _globals['_BUYERSERVICE']._serialized_end=945
# @@protoc_insertion_point(module_scope)
