# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buyer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import seller_pb2 as seller__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62uyer.proto\x12\x05\x62uyer\x1a\x0cseller.proto\"=\n\x11SearchItemRequest\x12\x11\n\titem_name\x18\x01 \x01(\t\x12\x15\n\rcategory_name\x18\x02 \x01(\t\"1\n\x12SearchItemResponse\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.seller.Item\"8\n\x0e\x42uyItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x15\n\ritem_quantity\x18\x02 \x01(\x05\"d\n\x0f\x42uyItemResponse\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.buyer.BuyItemResponse.Status\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\"\'\n\x14\x41\x64\x64ToWishListRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\"p\n\x15\x41\x64\x64ToWishListResponse\x12\x33\n\x06status\x18\x01 \x01(\x0e\x32#.buyer.AddToWishListResponse.Status\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\"2\n\x0fRateItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x0e\n\x06rating\x18\x02 \x01(\x05\"f\n\x10RateItemResponse\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.buyer.RateItemResponse.Status\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32\x94\x02\n\x0c\x42uyerService\x12\x41\n\nSearchItem\x12\x18.buyer.SearchItemRequest\x1a\x19.buyer.SearchItemResponse\x12\x38\n\x07\x42uyItem\x12\x15.buyer.BuyItemRequest\x1a\x16.buyer.BuyItemResponse\x12J\n\rAddToWishList\x12\x1b.buyer.AddToWishListRequest\x1a\x1c.buyer.AddToWishListResponse\x12;\n\x08RateItem\x12\x16.buyer.RateItemRequest\x1a\x17.buyer.RateItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buyer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SEARCHITEMREQUEST']._serialized_start=36
  _globals['_SEARCHITEMREQUEST']._serialized_end=97
  _globals['_SEARCHITEMRESPONSE']._serialized_start=99
  _globals['_SEARCHITEMRESPONSE']._serialized_end=148
  _globals['_BUYITEMREQUEST']._serialized_start=150
  _globals['_BUYITEMREQUEST']._serialized_end=206
  _globals['_BUYITEMRESPONSE']._serialized_start=208
  _globals['_BUYITEMRESPONSE']._serialized_end=308
  _globals['_BUYITEMRESPONSE_STATUS']._serialized_start=274
  _globals['_BUYITEMRESPONSE_STATUS']._serialized_end=308
  _globals['_ADDTOWISHLISTREQUEST']._serialized_start=310
  _globals['_ADDTOWISHLISTREQUEST']._serialized_end=349
  _globals['_ADDTOWISHLISTRESPONSE']._serialized_start=351
  _globals['_ADDTOWISHLISTRESPONSE']._serialized_end=463
  _globals['_ADDTOWISHLISTRESPONSE_STATUS']._serialized_start=274
  _globals['_ADDTOWISHLISTRESPONSE_STATUS']._serialized_end=308
  _globals['_RATEITEMREQUEST']._serialized_start=465
  _globals['_RATEITEMREQUEST']._serialized_end=515
  _globals['_RATEITEMRESPONSE']._serialized_start=517
  _globals['_RATEITEMRESPONSE']._serialized_end=619
  _globals['_RATEITEMRESPONSE_STATUS']._serialized_start=274
  _globals['_RATEITEMRESPONSE_STATUS']._serialized_end=308
  _globals['_BUYERSERVICE']._serialized_start=622
  _globals['_BUYERSERVICE']._serialized_end=898
# @@protoc_insertion_point(module_scope)
