#import grpc
import grpc

#import seller classes generated by grpc
import seller_pb2
import seller_pb2_grpc

#import buyer classes generated by grpc
import buyer_pb2
import buyer_pb2_grpc

#import market classes generated by grpc
import market_pb2
import market_pb2_grpc



class SellerServiceServicer(seller_pb2_grpc.SellerServiceServicer):
    """ Add methods to implement functionality of the services required by the seller"""

    def __init__(self):
        self.registered_sellers = {}

    def RegisterSeller(self, request, context):
        #extract uuid and add key to dictionary
        curr_seller_uuid = int(request.message)

        #validate user
        if (curr_seller_uuid in self.registered_sellers.keys()):
            return "FAILURE: USER ALREADY EXISTS"
        else:
            self.registered_sellers = []
            return "SUCCESS: USER ADDED"

    
    def SellItem(self, request, context):

        #retrieve item info
        curr_item_id = request.item.item_id
        curr_item_name = request.item.name
        curr_item_price = request.item.item_price
        curr_item_quantity = request.item.quantity
        curr_item_category = request.item.category
        curr_item_description = request.item.description
        curr_item_selleraddress = request.item.seller_address

        #retrieve seller id
        curr_seller_id = request.seller_id

        #retrieve uuid
        curr_seller_uuid = request.message
        