# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import buyer_pb2 as buyer__pb2
import seller_pb2 as seller__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmarket.proto\x12\x06market\x1a\x0b\x62uyer.proto\x1a\x0cseller.proto\"\x1f\n\x0cNotification\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x14NotificationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd0\x05\n\rMarketService\x12\x41\n\nSearchItem\x12\x18.buyer.SearchItemRequest\x1a\x19.buyer.SearchItemResponse\x12\x38\n\x07\x42uyItem\x12\x15.buyer.BuyItemRequest\x1a\x16.buyer.BuyItemResponse\x12J\n\rAddToWishList\x12\x1b.buyer.AddToWishListRequest\x1a\x1c.buyer.AddToWishListResponse\x12;\n\x08RateItem\x12\x16.buyer.RateItemRequest\x1a\x17.buyer.RateItemResponse\x12O\n\x0eRegisterSeller\x12\x1d.seller.RegisterSellerRequest\x1a\x1e.seller.RegisterSellerResponse\x12=\n\x08SellItem\x12\x17.seller.SellItemRequest\x1a\x18.seller.SellItemResponse\x12\x43\n\nUpdateItem\x12\x19.seller.UpdateItemRequest\x1a\x1a.seller.UpdateItemResponse\x12\x43\n\nDeleteItem\x12\x19.seller.DeleteItemRequest\x1a\x1a.seller.DeleteItemResponse\x12[\n\x12\x44isplaySellerItems\x12!.seller.DisplaySellerItemsRequest\x1a\".seller.DisplaySellerItemsResponse\x12\x42\n\x0cNotifyClient\x12\x14.market.Notification\x1a\x1c.market.NotificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFICATION']._serialized_start=51
  _globals['_NOTIFICATION']._serialized_end=82
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=84
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=123
  _globals['_MARKETSERVICE']._serialized_start=126
  _globals['_MARKETSERVICE']._serialized_end=846
# @@protoc_insertion_point(module_scope)
