# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import buyer_pb2 as buyer__pb2
import market_pb2 as market__pb2
import seller_pb2 as seller__pb2


class MarketServiceStub(object):
    """define services
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchItem = channel.unary_unary(
                '/market.MarketService/SearchItem',
                request_serializer=buyer__pb2.SearchItemRequest.SerializeToString,
                response_deserializer=buyer__pb2.SearchItemResponse.FromString,
                )
        self.BuyItem = channel.unary_unary(
                '/market.MarketService/BuyItem',
                request_serializer=buyer__pb2.BuyItemRequest.SerializeToString,
                response_deserializer=buyer__pb2.BuyItemResponse.FromString,
                )
        self.AddToWishList = channel.unary_unary(
                '/market.MarketService/AddToWishList',
                request_serializer=buyer__pb2.AddToWishListRequest.SerializeToString,
                response_deserializer=buyer__pb2.AddToWishListResponse.FromString,
                )
        self.RateItem = channel.unary_unary(
                '/market.MarketService/RateItem',
                request_serializer=buyer__pb2.RateItemRequest.SerializeToString,
                response_deserializer=buyer__pb2.RateItemResponse.FromString,
                )
        self.RegisterSeller = channel.unary_unary(
                '/market.MarketService/RegisterSeller',
                request_serializer=seller__pb2.RegisterSellerRequest.SerializeToString,
                response_deserializer=seller__pb2.RegisterSellerResponse.FromString,
                )
        self.SellItem = channel.unary_unary(
                '/market.MarketService/SellItem',
                request_serializer=seller__pb2.SellItemRequest.SerializeToString,
                response_deserializer=seller__pb2.SellItemResponse.FromString,
                )
        self.UpdateItem = channel.unary_unary(
                '/market.MarketService/UpdateItem',
                request_serializer=seller__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=seller__pb2.UpdateItemResponse.FromString,
                )
        self.DeleteItem = channel.unary_unary(
                '/market.MarketService/DeleteItem',
                request_serializer=seller__pb2.DeleteItemRequest.SerializeToString,
                response_deserializer=seller__pb2.DeleteItemResponse.FromString,
                )
        self.DisplaySellerItems = channel.unary_unary(
                '/market.MarketService/DisplaySellerItems',
                request_serializer=seller__pb2.DisplaySellerItemsRequest.SerializeToString,
                response_deserializer=seller__pb2.DisplaySellerItemsResponse.FromString,
                )
        self.NotifyClient = channel.unary_unary(
                '/market.MarketService/NotifyClient',
                request_serializer=market__pb2.Notification.SerializeToString,
                response_deserializer=market__pb2.NotificationResponse.FromString,
                )


class MarketServiceServicer(object):
    """define services
    """

    def SearchItem(self, request, context):
        """Buyer service methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuyItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToWishList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterSeller(self, request, context):
        """Seller service methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SellItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplaySellerItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyClient(self, request, context):
        """notify client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItem,
                    request_deserializer=buyer__pb2.SearchItemRequest.FromString,
                    response_serializer=buyer__pb2.SearchItemResponse.SerializeToString,
            ),
            'BuyItem': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyItem,
                    request_deserializer=buyer__pb2.BuyItemRequest.FromString,
                    response_serializer=buyer__pb2.BuyItemResponse.SerializeToString,
            ),
            'AddToWishList': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToWishList,
                    request_deserializer=buyer__pb2.AddToWishListRequest.FromString,
                    response_serializer=buyer__pb2.AddToWishListResponse.SerializeToString,
            ),
            'RateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RateItem,
                    request_deserializer=buyer__pb2.RateItemRequest.FromString,
                    response_serializer=buyer__pb2.RateItemResponse.SerializeToString,
            ),
            'RegisterSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSeller,
                    request_deserializer=seller__pb2.RegisterSellerRequest.FromString,
                    response_serializer=seller__pb2.RegisterSellerResponse.SerializeToString,
            ),
            'SellItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SellItem,
                    request_deserializer=seller__pb2.SellItemRequest.FromString,
                    response_serializer=seller__pb2.SellItemResponse.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=seller__pb2.UpdateItemRequest.FromString,
                    response_serializer=seller__pb2.UpdateItemResponse.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=seller__pb2.DeleteItemRequest.FromString,
                    response_serializer=seller__pb2.DeleteItemResponse.SerializeToString,
            ),
            'DisplaySellerItems': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplaySellerItems,
                    request_deserializer=seller__pb2.DisplaySellerItemsRequest.FromString,
                    response_serializer=seller__pb2.DisplaySellerItemsResponse.SerializeToString,
            ),
            'NotifyClient': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyClient,
                    request_deserializer=market__pb2.Notification.FromString,
                    response_serializer=market__pb2.NotificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'market.MarketService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarketService(object):
    """define services
    """

    @staticmethod
    def SearchItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market.MarketService/SearchItem',
            buyer__pb2.SearchItemRequest.SerializeToString,
            buyer__pb2.SearchItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BuyItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market.MarketService/BuyItem',
            buyer__pb2.BuyItemRequest.SerializeToString,
            buyer__pb2.BuyItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddToWishList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market.MarketService/AddToWishList',
            buyer__pb2.AddToWishListRequest.SerializeToString,
            buyer__pb2.AddToWishListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market.MarketService/RateItem',
            buyer__pb2.RateItemRequest.SerializeToString,
            buyer__pb2.RateItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market.MarketService/RegisterSeller',
            seller__pb2.RegisterSellerRequest.SerializeToString,
            seller__pb2.RegisterSellerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SellItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market.MarketService/SellItem',
            seller__pb2.SellItemRequest.SerializeToString,
            seller__pb2.SellItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market.MarketService/UpdateItem',
            seller__pb2.UpdateItemRequest.SerializeToString,
            seller__pb2.UpdateItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market.MarketService/DeleteItem',
            seller__pb2.DeleteItemRequest.SerializeToString,
            seller__pb2.DeleteItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisplaySellerItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market.MarketService/DisplaySellerItems',
            seller__pb2.DisplaySellerItemsRequest.SerializeToString,
            seller__pb2.DisplaySellerItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market.MarketService/NotifyClient',
            market__pb2.Notification.SerializeToString,
            market__pb2.NotificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
