# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmarket.proto\"\x1f\n\x0cNotification\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x14NotificationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2E\n\rMarketService\x12\x34\n\x0cNotifyClient\x12\r.Notification\x1a\x15.NotificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFICATION']._serialized_start=16
  _globals['_NOTIFICATION']._serialized_end=47
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=49
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=88
  _globals['_MARKETSERVICE']._serialized_start=90
  _globals['_MARKETSERVICE']._serialized_end=159
# @@protoc_insertion_point(module_scope)
