#import grpc
import grpc

#import seller classes generated by grpc
import seller_pb2
import seller_pb2_grpc

#import buyer classes generated by grpc
import buyer_pb2
import buyer_pb2_grpc

#import market classes generated by grpc
import market_pb2
import market_pb2_grpc

class ProductDetails:
    def __init__(self, name, item_price, quantity, category, description, seller_address):
        self.name = name
        self.item_price = item_price
        self.quantity = quantity
        self.category = category
        self.description = description
        self.seller_address = seller_address

        

class MarketServiceServicer(market_pb2_grpc.MarketServiceServicer):
    """ Add methods to implement functionality of the services required by the seller"""

    def __init__(self):
        self.registered_sellers = {}
        self.products={}#product_id to ProductDetails

    def RegisterSeller(self, request, context):
        #extract uuid and add key to dictionary
        curr_seller_uuid = request.message

        #validate user
        if (curr_seller_uuid in self.registered_sellers.keys()):
            return "FAILURE: USER ALREADY EXISTS"
        else:
            self.registered_sellers = []
            return "SUCCESS: USER ADDED"

    
    def SellItem(self, request, context):

        #retrieve item info
        curr_item_id = request.item.item_id
        curr_item_name = request.item.name
        curr_item_price = request.item.item_price
        curr_item_quantity = request.item.quantity
        curr_item_category = request.item.category
        curr_item_description = request.item.description
        curr_item_selleraddress = request.item.seller_address

        #retrieve seller id
        curr_seller_id = request.seller_id

        #retrieve uuid
        curr_seller_uuid = request.message
    
    def SearchItem(self, request,context):
    
    def BuyItem(self, request, context):

    def AddToWishList(self, request, context):

    def RateItem(self, request, context):
